mytestkey=This value is from LOCAL properties file

#TODO: move this to secrets manager

stripe.create-session.url=https://api.stripe.com/v1/checkout/sessions
stripe.get-session.url=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire-session.url=https://api.stripe.com/v1/checkout/sessions/{id}/expire

#Ollama for laama 3.2
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b

processing.notification.url=http://localhost:8082/v1/payments/notifications

stripe.api.key=sk_test_51Rad1zFab3ReIkyOfCz53Z1j2XR6g5IhzNIhJGZURMn0NwRWpmUJ2uX1SEPdftmdCwcslfyuEgOtFz4RcU39VJ7x00rszTpXFP

stripe.webhook.secret=whsec_edb902457052dc6982bf7da844d6a6f09d5ca3981c646e6cc42d339477a76b5c

