mytestkey=This value is from LOCAL properties file

#TODO: move this to secrets manager

stripe.create-session.url=https://api.stripe.com/v1/checkout/sessions
stripe.get-session.url=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire-session.url=https://api.stripe.com/v1/checkout/sessions/{id}/expire

#Ollama for laama 3.2
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b

processing.notification.url=http://localhost:8082/v1/payments/notifications

#stripe.api.key=${STRIPE_API_KEY}
#
#stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
#
